name: tube

# # Actualisation du flux toutes les 3 heures. 
on:
  schedule:
    - cron: '0 0/3 * * *'

  # Permet d'exécuter ce flux de travail manuellement à partir de l'onglet Actions
  workflow_dispatch:

permissions:
  contents: write

# Un flux de travail se compose d'une ou plusieurs tâches qui peuvent être exécutées séquentiellement ou en parallèle
jobs:
  # Ce flux de travail contient une tâche appelée "build"
  build:
    # Le travail sera exécuté sur ubuntu-latest
    runs-on: ubuntu-latest

    # Steps représentent une séquence de tâches qui seront exécutées dans le cadre du travail
    steps:
      # Extrait votre référentiel sous $GITHUB_WORKSPACE, afin que votre travail puisse y accéder
      - uses: actions/checkout@v3


      # Pour pouvoir travailler sur un projet,
      # Vous avez besoin d’un nom d’utilisateur et d’une adresse email associée valide. 
      - name: config
        run: |
          git pull
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: actualisation des flux
        run: |
          pwd
          python3 tube.py "https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live" > france24.m3u8
          sleep 15
          python3 tube.py "https://www.youtube.com/channel/UCW2QcKZiU8aUGg4yxCIditg/live" > euronews.m3u8
          sleep 15
          python3 tube.py "https://www.youtube.com/channel/UCT67YOMntJxfRnO_9bXDpvw/live" > lemedia.m3u8
          sleep 15
          python3 tube.py "https://www.youtube.com/channel/UC25EuGAePOPvPrUA5cmu3dQ/live" > africanews.m3u8
          sleep 15
          python3 tube.py "https://www.youtube.com/channel/UCUaHJ0fTA-1theR8A8Polmw/live" > techandco.m3u8
          sleep 15
          python3 tube.py "https://www.youtube.com/channel/UCYhS-Sw_IKM9CZLPd3QS-BQ/live" > relaxnature.m3u8
          
        

      # Informer Git que vous voulez inclure les mises à jour dans un fichier.
      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit & push
        run: |
          git commit -m "Actualisation des flux"
          git push
